name: Gradle Project Integration Tests 

on:
  workflow_call:
    inputs:
      version-label:
        required: true
        type: string

jobs:

  # TODO: The Monkey seems to crash the app all the time, but with failures that are not coming from the app. Figure out why.
  # android-sample-app:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup Java 11
  #       uses: actions/setup-java@v3
  #       with:
  #         distribution: zulu
  #         java-version: 11

  #     - name: Setup Gradle and task/dependency caching
  #       uses: gradle/gradle-build-action@v2
  #       with:
  #         cache-read-only: false

  #     - name: Restore m2-buildrepo
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: all-packages-${{ needs.check-cache.outputs.version-label }}
  #         path: ./packages/build/m2-buildrepo 

  #     # TODO Can we read api level from Config.kt
  #     - name: Run Monkey on Android Sample 
  #       env:
  #         SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  #       uses: reactivecircus/android-emulator-runner@v2
  #       with:
  #         api-level: 33
  #         target: google_apis # default is not available on 33 yet.
  #         arch: x86_64
  #         profile: Nexus 6
  #         disk-size: 4096M
  #         ram-size: 2048M
  #         heap-size: 1024M
  #         script: |
  #               cd examples/kmm-sample && ./gradlew installRelease
  #               $ANDROID_SDK_ROOT/platform-tools/adb shell monkey --throttle 50 --pct-syskeys 0 -p  io.realm.example.kmmsample.androidApp -v 500 --kill-process-after-error


  android-min-versions-compatibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Gradle and task/dependency caching
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false

      - name: Restore m2-buildrepo
        uses: actions/download-artifact@v3
        with:
          name: all-packages-${{ inputs.version-label }}
          path: ./packages/build/m2-buildrepo 

      # TODO Can we read api level from Config.kt
      - name: Build Android on minimum versions 
        working-directory: examples/min-android-sample
        run: |
          java --version
          ./gradlew assembleDebug jvmJar

  realm-java-compatibiliy:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Gradle and task/dependency caching
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false

      - name: Restore m2-buildrepo
        uses: actions/download-artifact@v3
        with:
          name: all-packages-${{ inputs.version-label }}
          path: ./packages/build/m2-buildrepo 

      # TODO Can we read api level from Config.kt
      - name: Run compatibility checks with Realm Java
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis # default is not available on 33 yet.
          arch: x86_64
          profile: Nexus 6
          disk-size: 4096M
          ram-size: 2048M
          heap-size: 1024M
          script: cd examples/realm-java-compatibility && ./gradlew connectedAndroidTest -PincludeSdkModules=false

      # TODO: This fails with `Error: Cannot read property 'trim' of undefined`. Possible a bug in the action.
      #  For now, just disable this as there is only a single unit test anyway.
      # - name: Publish Unit Test Results
      #   uses: dorny/test-reporter@v1
      #   if: always() || failure()
      #   with:
      #     name: Results - Realm Java Compatibility
      #     path: ./examples/realm-java-compatibility/app/build/**/TEST-*.xml
      #     reporter: java-junit
      #     list-suites: failed
      #     list-tests: failed
      #     fail-on-error: true

  build-benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Gradle and task/dependency caching
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false

      - name: Restore m2-buildrepo
        uses: actions/download-artifact@v3
        with:
          name: all-packages-${{ inputs.version-label }}
          path: ./packages/build/m2-buildrepo 

      - name: Build benchmarks
        working-directory: benchmarks
        run: ./gradlew assemble

  gradle-plugin-integration:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Gradle and task/dependency caching
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false

      - name: Restore m2-buildrepo
        uses: actions/download-artifact@v3
        with:
          name: all-packages-${{ inputs.version-label }}
          path: ./packages/build/m2-buildrepo 

      - name: Run Gradle Plugin Test project
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis # default is not available on 33 yet.
          arch: x86_64
          profile: Nexus 6
          disk-size: 4096M
          ram-size: 2048M
          heap-size: 1024M
          script: cd integration-tests/gradle-plugin-test && ./gradlew integrationTest
